swagger: '2.0'
info:
  contact:
    name: OneLogin
    url: 'https://support.onelogin.com'
  description: OpenAPI Specification for OneLogin
  title: OneLogin API
  version: 3.1.1
host: your-api-subdomain.onelogin.com
basePath: /api
schemes:
  - https
security:
  - apikey_auth: []

securityDefinitions:
  apikey_auth:
    type: "apiKey"
    in: "header"
    name: Authorization
    # name: "something" the name paramter will be ignored when using the 'x-terraform-authentication-scheme-bearer' extension, "Authorization" name will be use as default value
    x-terraform-authentication-scheme-bearer: true
paths:
  /2/apps:
    post:
      x-terraform-resource-name: "apps"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - default: application/json
          in: header
          name: Content-Type
          type: string
          x-example: application/json
        - in: body
          name: body
          schema:
            $ref: '#/definitions/oidc-app'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/oidc-app'
        '401':
          description: Unauthorized
          examples:
            application/json:
              code: 401
              error: true
              message: Unauthorized Error
              type: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '422':
          description: Unprocessable
          examples:
            application/json:
              code: 422
              error: true
              message: 'Validation failed: Value has already been taken'
              type: UnprocessableEntityError
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Apps
      description: Create App
      operationId: createApp
      summary: Create App
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/oidc-app'
            type: array
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: This request requires Authentication
              name: UnauthorizedError
              statusCode: 401
          schema:
            $ref: '#/definitions/altErr'
        '422':
          description: Unprocessable Entity
          examples:
            application/json:
              message: invalid value in \"auth_method\"
              name: UnprocessableEntityError
              statusCode: 422
          schema:
            $ref: '#/definitions/altErr'
      tags:
        - Apps
      description: List Apps
      operationId: listApps
      summary: List Apps
  '/2/apps/{id}':
    get:
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/oidc-app'
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: This request requires Authentication
              name: UnauthorizedError
              statusCode: 401
          schema:
            $ref: '#/definitions/altErr'
        '404':
          description: Not Found
          examples:
            application/json:
              message: >-
                The resource can't be found or the server has not found anything
                matching the Request-URI
              name: NotFoundError
              statusCode: 404
          schema:
            $ref: '#/definitions/altErr'
      tags:
        - Apps
      description: Get App
      operationId: getApp
      summary: Get App
    delete:
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: This request requires Authentication
              name: UnauthorizedError
              statusCode: 401
          schema:
            $ref: '#/definitions/altErr'
        '404':
          description: Not Found
          examples:
            application/json:
              message: >-
                The resource can't be found or the server has not found anything
                matching the Request-URI
              name: NotFoundError
              statusCode: 404
          schema:
            $ref: '#/definitions/altErr'
      tags:
        - Apps
      description: Delete App
      operationId: deleteApp
      summary: Delete App
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - in: body
          name: body
          schema:
            $ref: '#/definitions/oidc-app'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/oidc-app'
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: This request requires Authentication
              name: UnauthorizedError
              statusCode: 401
          schema:
            $ref: '#/definitions/altErr'
        '404':
          description: Not Found
          examples:
            application/json:
              message: >-
                The resource can't be found or the server has not found anything
                matching the Request-URI
              name: NotFoundError
              statusCode: 404
          schema:
            $ref: '#/definitions/altErr'
      tags:
        - Apps
      description: Update App
      operationId: updateApp
      summary: Update App
parameters:
  id:
    name: id
    in: path
    required: true
    type: string
    description: resource id
tags:
  - name: Apps
definitions:
  altErr:
    properties:
      message:
        description: Description of Error
        example: Settings Updated
        type: string
      name:
        description: Error Code Name
        example: Success
        type: string
      statusCode:
        description: >-
          HTTP error code
          https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
        example: 200
        type: integer
    type: object
  Error:
    properties:
      code:
        example: 200
        type: integer
      error:
        example: false
        type: boolean
      message:
        example: Success
        type: string
      type:
        example: Success
        type: string
    required:
      - code
      - message
    type: object
  oidc-app:
    x-terraform-computed: true
    properties:
      auth_method_description:
        type: string
        example: "OpenId Connect"
        readOnly: true
      brand_id:
        type: integer
      login_config:
        type: integer
        readOnly: true
        example: 0
      configuration:
        description: Only apply configurations that are applicable to the type of app
        x-terraform-computed: true
        type: object
        properties: 
          redirect_uri:
            type: string
            description: >-
              OIDC Apps only
              Comma or newline separated list of valid redirect uris for the OpenId Connect Authorization Code flow.
          login_url:
            type: string
            description: >-
              OIDC Apps only
              The OpenId Connect Client Id. Note that client_secret is only returned after Creating an App.
          oidc_api_version:
            type: string
            readOnly: true
          oidc_encryption_key:
            type: string
            description: OIDC Apps only
          post_logout_redirect_uri:
            type: string
            description: OIDC Apps only
          refresh_token_expiration_minutes:
            type: integer
            description: Number of minutes the refresh token will be valid for.
          oidc_application_type:
            type: integer
            description: >-
              OIDC Apps Only
                - 0: Web
                - 1: Native/Mobile
          token_endpoint_auth_method:
            type: integer
            description: >-
              OIDC Apps only
              - 0: Basic
              - 1: POST
              - 2: None / PKCE
          access_token_expiration_minutes:
            type: integer
            description: >-
              OIDC Apps only
              Number of minutes the refresh token will be valid for.
      allow_assumed_signin:
        description: >-
          Indicates whether or not administrators can access the app as a user
          that they have assumed control over.
        example: false
        type: boolean
      auth_method:
        $ref: '#/definitions/auth_method'
      connector_id:
        description: ID of the connector to base the app from.
        example: 108419
        type: integer
      created_at:
        description: the date the app was created
        example: '2018-04-12T21:50:42Z'
        type: string
        readOnly: true
      description:
        description: Freeform description of the app.
        type: string
      enforcement_point:
        $ref: '#/definitions/enforcement_point'
      icon_url:
        description: A link to the apps icon url
        example: /images/missing_connector_icon/square/old_original.png
        type: string
      id:
        description: Apps unique ID in OneLogin.
        example: 775664
        readOnly: true
        type: integer
      name:
        description: The name of the app.
        example: A Sample App
        type: string
      notes:
        description: Freeform notes about the app.
        example: This app is in beta.
        type: string
      policy_id:
        description: The security policy assigned to the app.
        type: integer
      provisioning:
        description: Indicates if provisioning is enabled for this app.
        properties:
          enabled:
            example: true
            type: boolean
          status:
            type: string
            readOnly: true
        type: object
      role_ids:
        description: >-
          List of Role IDs that are assigned to the app. On App Create or Update
          the entire array is replaced with the values provided.
        example:
          - 192513
        items:
          description: Role ID
          type: integer
        type: array
      sso:
        description: >-
          The attributes included in the sso section are determined by the type of app.
          All of the attributes of the `sso` object are read only.
        type: object
        readOnly: true
        properties: 
          client_id:
            type: string
            description: The OpenId Connect Client Id. Note that client_secret is only returned after Creating an OIDC App.
            readOnly: true
          client_secret:
            type: string
            description: OpenId Connet Client Secret
            readOnly: true
      tab_id:
        description: ID of the OneLogin portal tab that the app is assigned to.
        example: 196885
        type: integer
      updated_at:
        description: the date the app was last updated
        example: '2019-05-16T19:20:34Z'
        type: string
        readOnly: true
      visible:
        description: Indicates if the app is visible in the OneLogin portal.
        example: true
        type: boolean
      parameters:
        type: object
        x-terraform-computed: true
        additionalProperties:
          type: object
          x-terraform-computed: true
          additionalProperties: 
            type: string
            x-terraform-computed: true
        properties: 
          groups:
            type: object
            properties: 
              provisioned_entitlements:
                type: boolean
                example: false
              label:
                type: string
                example: Groups
              skip_if_blank:
                type: boolean
                example: false
              user_attribute_mappings:
                type: string
              user_attribute_macros:
                type: string
              default_values:
                type: string
              values:
                type: string
              attributes_transformations:
                type: string
              id:
                type: integer
                example: 237825
    required:
      - connector_id
      - name
    type: object
  auth_method:
    description: |-
      An ID indicating the type of app:
        - 0: Password
        - 1: OpenId
        - 2: SAML
        - 3: API
        - 4: Google
        - 6: Forms Based App
        - 7: WSFED
        - 8: OpenId Connect
    enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    example: 8
    type: integer
  enforcement_point:
    description: >-
      For apps that connect to a OneLogin Access Enforcement Point the following
      enforcement_point object will be included with the app payload.
    properties:
      case_sensitive:
        description: >-
          The URL path evaluation is case insensitive by default. Resources
          hosted on web servers such as Apache, NGINX and Java EE are case
          sensitive paths. Web servers such as Microsoft IIS are not
          case-sensitive.
        example: false
        type: boolean
      conditions:
        description: >-
          If access is conditional, the conditions that must evaluate to true to
          allow access to a resource. For example, to require the user must be
          authenticated and have either the role Admin or User
        example: ''
        type: string
      context_root:
        description: >-
          The root path to the application, often the name of the application.
          Can be any name, path or just a slash (“/”). The context root uniquely
          identifies the application within the enforcement point.
        example: /
        type: string
      landing_page:
        description: >-
          The location within the context root to which the browser will be
          redirected for IdP-initiated single sign-on. For example, the landing
          page might be an index page in the context root such as index.html or
          default.aspx. The landing page cannot begin with a slash and must use
          valid URL characters.
        example: ''
        type: string
        x-nullable: true
      permissions:
        description: >-
          Specify to always `allow`, `deny` access to resources, of if access is
          `conditional`.
        enum:
          - allow
          - deny
          - conditional
        example: allow
        type: string
      require_sitewide_authentication:
        description: >-
          Require user authentication to access any resource protected by this
          enforcement point.
        example: false
        type: boolean
      resources:
        description: Array of resource objects
        example:
          - conditions: ''
            is_path_regex: false
            path: /
            permissions: allow
            require_auth: false
            resource_id: 809
        items:
          properties:
            conditions:
              description: required if permission == "conditions"
              type: string
            is_path_regex:
              type: boolean
              x-nullable: true
            path:
              example: /
              type: string
            permission:
              enum:
                - allow
                - deny
                - conditions
              type: string
            require_auth:
              example: false
              type: boolean
          type: object
        type: array
      session_expiry_fixed:
        $ref: '#/definitions/clock_counter'
      session_expiry_inactivity:
        $ref: '#/definitions/clock_counter'
      target:
        description: >-
          A fully-qualified URL to the internal application including scheme,
          authority and path. The target host authority must be an IP address,
          not a hostname.
        example: ''
        type: string
        x-nullable: true
      token:
        description: Can only be set on create. Access Gateway Token.
        example: b491c647f5e0cff854ad606722ac98342b4b0882
        readOnly: true
        type: string
      use_target_host_header:
        description: >-
          Use the target host header as opposed to the original gateway or
          upstream host header.
        example: false
        type: boolean
      vhost:
        description: >-
          A comma-delimited list of one or more virtual hosts that map to
          applications assigned to the enforcement point. A VHOST may be a host
          name or an IP address. VHOST distinguish between applications that are
          at the same context root.
        example: ''
        type: string
        x-nullable: true
    type: object
  clock_counter:
    description: >-
      unit: - 0 = Seconds - 1 = Minutes - 2 = Hours value: - When Unit = 0 or 1
      value must be 0-60 - When Unit = 2 value must be 0-24
    example:
      unit: 1
      value: 30
    properties:
      unit:
        type: integer
      value:
        type: integer
    type: object
